services:
  vcds:
    image: koko004/vcds:latest
    container_name: vcds
    ports:
      - "8000:8000"
    volumes:
      - vcds_data:/app/uploads
      - vcds_originales:/app/originales
      - vcds_config:/app/config.json
      - vcds_auth:/app/auth.json
    restart: unless-stopped
    environment:
      - DISPLAY=:99

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 vcds
    restart: unless-stopped

volumes:
  vcds_data:
  vcds_originales:
  vcds_config:
  vcds_auth:
