services:
  vcds:
    image: koko004/vcds:latest
    container_name: vcds
    ports:
      - "4776:4776"
    volumes:
      - vcds_data:/app/uploads
      - vcds_originales:/app/originales
    restart: unless-stopped
    environment:
      - DISPLAY=:99

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup vcds
    restart: unless-stopped

volumes:
  vcds_data:
  vcds_originales:
